description: |
  Create a kubernetes deployment.

usage:
  version: 2.1

  orbs:
    aws-eks: circleci/aws-eks@0.2.3
    kubernetes: circleci/kubernetes@0.4.0

  jobs:
    create-deployment:
      executor: aws-eks/python3
      parameters:
        cluster-name:
          description: |
            Name of the EKS cluster
          type: string
      steps:
        - checkout
        - aws-eks/update-kubeconfig-with-authenticator:
            cluster-name: << parameters.cluster-name >>
            install-kubectl: true
        - kubernetes/create-or-update-resource:
            resource-file-path: "tests/nginx-deployment/deployment.yaml"
            resource-name: "deployment/nginx-deployment"
            get-rollout-status: true

  workflows:
    deployment:
      jobs:
        - aws-eks/create-cluster:
            cluster-name: eks-demo-deployment
        - create-deployment:
            cluster-name: eks-demo-deployment
            requires:
              - aws-eks/create-cluster
        - aws-eks/update-container-image:
            cluster-name: eks-demo-deployment
            resource-name: "deployment/nginx-deployment"
            container-image-updates: "nginx=nginx:1.9.1"
            record: true
            requires:
              - create-deployment
            post-steps:
              - kubernetes/delete-resource:
                  resource-types: "deployment"
                  resource-names: "nginx-deployment"
                  wait: true
        - aws-eks/delete-cluster:
            cluster-name: eks-demo-deployment
            requires:
              - aws-eks/update-container-image
